import { z } from "zod";
export declare const PresenceModeSchema: z.ZodEnum<["active", "semi_active", "lurking", "busy_elsewhere", "avoidant", "offline"]>;
export declare const BudgetPrioritySchema: z.ZodEnum<["high", "normal", "low", "blocked"]>;
export declare const PersonaConfigSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    archetype: z.ZodString;
    writingStyle: z.ZodString;
    styleExamples: z.ZodArray<z.ZodString, "many">;
    baselineValence: z.ZodNumber;
    baselineArousal: z.ZodNumber;
    baselineStability: z.ZodNumber;
    baselineEnergy: z.ZodNumber;
    emotionalReactivity: z.ZodNumber;
    moodInertia: z.ZodNumber;
    maxMoodRotation: z.ZodNumber;
    energyRegen: z.ZodNumber;
    exclusionSensitivity: z.ZodNumber;
    praiseSensitivity: z.ZodNumber;
    conflictSensitivity: z.ZodNumber;
    boredomSensitivity: z.ZodNumber;
    intimacySensitivity: z.ZodNumber;
    socialSensitivities: z.ZodRecord<z.ZodString, z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    id: string;
    name: string;
    archetype: string;
    writingStyle: string;
    styleExamples: string[];
    baselineValence: number;
    baselineArousal: number;
    baselineStability: number;
    baselineEnergy: number;
    emotionalReactivity: number;
    moodInertia: number;
    maxMoodRotation: number;
    energyRegen: number;
    exclusionSensitivity: number;
    praiseSensitivity: number;
    conflictSensitivity: number;
    boredomSensitivity: number;
    intimacySensitivity: number;
    socialSensitivities: Record<string, number>;
}, {
    id: string;
    name: string;
    archetype: string;
    writingStyle: string;
    styleExamples: string[];
    baselineValence: number;
    baselineArousal: number;
    baselineStability: number;
    baselineEnergy: number;
    emotionalReactivity: number;
    moodInertia: number;
    maxMoodRotation: number;
    energyRegen: number;
    exclusionSensitivity: number;
    praiseSensitivity: number;
    conflictSensitivity: number;
    boredomSensitivity: number;
    intimacySensitivity: number;
    socialSensitivities: Record<string, number>;
}>;
//# sourceMappingURL=agent.schema.d.ts.map