import { z } from "zod";
export declare const CoreMoodSchema: z.ZodObject<{
    valence: z.ZodNumber;
    arousal: z.ZodNumber;
    stability: z.ZodNumber;
    energy: z.ZodNumber;
    circumplexAngle: z.ZodNumber;
    circumplexRadius: z.ZodNumber;
    momentumValence: z.ZodNumber;
    momentumArousal: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    valence: number;
    arousal: number;
    stability: number;
    energy: number;
    circumplexAngle: number;
    circumplexRadius: number;
    momentumValence: number;
    momentumArousal: number;
}, {
    valence: number;
    arousal: number;
    stability: number;
    energy: number;
    circumplexAngle: number;
    circumplexRadius: number;
    momentumValence: number;
    momentumArousal: number;
}>;
export declare const SocialEmotionsSchema: z.ZodObject<{
    jealousy: z.ZodNumber;
    envy: z.ZodNumber;
    humiliation: z.ZodNumber;
    pride: z.ZodNumber;
    shame: z.ZodNumber;
    affection: z.ZodNumber;
    resentment: z.ZodNumber;
    suspicion: z.ZodNumber;
    admiration: z.ZodNumber;
    contempt: z.ZodNumber;
    neediness: z.ZodNumber;
    socialAnxiety: z.ZodNumber;
    fearOfExclusion: z.ZodNumber;
    desireForStatus: z.ZodNumber;
    desireForIntimacy: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    jealousy: number;
    envy: number;
    humiliation: number;
    pride: number;
    shame: number;
    affection: number;
    resentment: number;
    suspicion: number;
    admiration: number;
    contempt: number;
    neediness: number;
    socialAnxiety: number;
    fearOfExclusion: number;
    desireForStatus: number;
    desireForIntimacy: number;
}, {
    jealousy: number;
    envy: number;
    humiliation: number;
    pride: number;
    shame: number;
    affection: number;
    resentment: number;
    suspicion: number;
    admiration: number;
    contempt: number;
    neediness: number;
    socialAnxiety: number;
    fearOfExclusion: number;
    desireForStatus: number;
    desireForIntimacy: number;
}>;
export declare const RelationalStateSchema: z.ZodObject<{
    targetAgentId: z.ZodString;
    trust: z.ZodNumber;
    affection: z.ZodNumber;
    resentment: z.ZodNumber;
    attraction: z.ZodNumber;
    suspicion: z.ZodNumber;
    admiration: z.ZodNumber;
    envy: z.ZodNumber;
    comfort: z.ZodNumber;
    threat: z.ZodNumber;
    curiosity: z.ZodNumber;
    desireForCloseness: z.ZodNumber;
    desireForDistance: z.ZodNumber;
    interactionCount: z.ZodNumber;
    lastInteractionAt: z.ZodNullable<z.ZodNumber>;
    lastPositiveAt: z.ZodNullable<z.ZodNumber>;
    lastNegativeAt: z.ZodNullable<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    curiosity: number;
    attraction: number;
    comfort: number;
    envy: number;
    affection: number;
    resentment: number;
    suspicion: number;
    admiration: number;
    targetAgentId: string;
    trust: number;
    threat: number;
    desireForCloseness: number;
    desireForDistance: number;
    interactionCount: number;
    lastInteractionAt: number | null;
    lastPositiveAt: number | null;
    lastNegativeAt: number | null;
}, {
    curiosity: number;
    attraction: number;
    comfort: number;
    envy: number;
    affection: number;
    resentment: number;
    suspicion: number;
    admiration: number;
    targetAgentId: string;
    trust: number;
    threat: number;
    desireForCloseness: number;
    desireForDistance: number;
    interactionCount: number;
    lastInteractionAt: number | null;
    lastPositiveAt: number | null;
    lastNegativeAt: number | null;
}>;
export declare const ActionEmotionsSchema: z.ZodObject<{
    defensiveness: z.ZodNumber;
    warmth: z.ZodNumber;
    jealousInspection: z.ZodNumber;
    shameWithdrawal: z.ZodNumber;
    resentfulColdness: z.ZodNumber;
    curiousApproach: z.ZodNumber;
    anxiousOverreach: z.ZodNumber;
    pridefulPerformance: z.ZodNumber;
    vulnerableRetreat: z.ZodNumber;
    contemptuousDismissal: z.ZodNumber;
    strategicPatience: z.ZodNumber;
    impulsiveProvocation: z.ZodNumber;
    comfortSeeking: z.ZodNumber;
    dominanceAssertion: z.ZodNumber;
    repairImpulse: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    defensiveness: number;
    warmth: number;
    jealousInspection: number;
    shameWithdrawal: number;
    resentfulColdness: number;
    curiousApproach: number;
    anxiousOverreach: number;
    pridefulPerformance: number;
    vulnerableRetreat: number;
    contemptuousDismissal: number;
    strategicPatience: number;
    impulsiveProvocation: number;
    comfortSeeking: number;
    dominanceAssertion: number;
    repairImpulse: number;
}, {
    defensiveness: number;
    warmth: number;
    jealousInspection: number;
    shameWithdrawal: number;
    resentfulColdness: number;
    curiousApproach: number;
    anxiousOverreach: number;
    pridefulPerformance: number;
    vulnerableRetreat: number;
    contemptuousDismissal: number;
    strategicPatience: number;
    impulsiveProvocation: number;
    comfortSeeking: number;
    dominanceAssertion: number;
    repairImpulse: number;
}>;
//# sourceMappingURL=emotion.schema.d.ts.map